name: Nitpicker
on: [pull_request_target]
permissions:
  pull-requests: write
jobs:
  formatting-check:
    name: tag codeowners
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: nitpicker
      uses: ethanis/nitpicker@v1.6
      with:
        nitpicks: './.github/nitpicks.yml'
        token: '${{ secrets.GITHUB_TOKEN }}'
